'use strict';

window.PORTFOLIO_I18N = {
  supported: ['en', 'pl', 'ru', 'uk'],
  labels: {
    en: { short: 'EN', name: 'English' },
    pl: { short: 'PL', name: 'Polski' },
    ru: { short: 'RU', name: 'Русский' },
    uk: { short: 'UA', name: 'Українська' }
  },
  meta: {
    en: {
      title: 'Dmytro Poliakov — Junior DevOps Portfolio',
      description: 'Dmytro Poliakov — aspiring Junior DevOps engineer, AWS Certified Cloud Practitioner and Computer Science student. Explore Docker CI, Linux practice and an operations background.'
    },
    pl: {
      title: 'Dmytro Poliakov — Portfolio Junior DevOps',
      description: 'Dmytro Poliakov — kandydat na stanowisko Junior DevOps, AWS Certified Cloud Practitioner i student informatyki. Projekty Docker CI, praktyka z Linuksem i doświadczenie operacyjne.'
    },
    ru: {
      title: 'Dmytro Poliakov — Портфолио Junior DevOps',
      description: 'Dmytro Poliakov — начинающий Junior DevOps, AWS Certified Cloud Practitioner и студент информатики. Проекты Docker CI, практика Linux и опыт в операционной работе.'
    },
    uk: {
      title: 'Dmytro Poliakov — Портфоліо Junior DevOps',
      description: 'Dmytro Poliakov — початківець Junior DevOps, AWS Certified Cloud Practitioner і студент інформатики. Проєкти Docker CI, практика Linux та досвід в операційній роботі.'
    }
  },
  theme: {
    en: { darkAction: 'Switch to dark theme', lightAction: 'Switch to light theme', darkLabel: 'Dark', lightLabel: 'Light' },
    pl: { darkAction: 'Przełącz na ciemny motyw', lightAction: 'Przełącz na jasny motyw', darkLabel: 'Ciemny', lightLabel: 'Jasny' },
    ru: { darkAction: 'Переключить на тёмную тему', lightAction: 'Переключить на светлую тему', darkLabel: 'Тёмная', lightLabel: 'Светлая' },
    uk: { darkAction: 'Перемкнути на темну тему', lightAction: 'Перемкнути на світлу тему', darkLabel: 'Темна', lightLabel: 'Світла' }
  },
  ui: {
    en: {
      languageLabel: 'Change language', resultCount: n => `Showing ${n} project${n === 1 ? '' : 's'}`,
      dialogNumber: n => `PROJECT ${n} / LEARNING LAB`, repoView: 'View GitHub repository ↗', repoTitle: 'GitHub repository', repoMissing: 'Link to be added',
      simulating: 'Simulating…', pipelineRunning: 'Running the example workflow…', waiting: 'Waiting', running: 'Running…', failed: 'Failed', skipped: 'Skipped', passed: 'Passed', runAgain: 'Run again ▷',
      pipelineIntro: '$ run-example-workflow\n[SIMULATION] All output below is illustrative.\n',
      pipelineLines: ['✓ Example repository checked out', '✓ Docker image built: devops-docker-demo', '✓ Example container started on localhost:5000', '✓ Local GET /health → 200 {"status":"ok"}'],
      pipelineFailConsole: '✗ docker build: dependency installation failed\n— No new image available\n— Container start and local health check skipped\n',
      pipelineFailResult: 'Example failed: inspect the dependency error and fix the build before running the container. No deployment occurred.',
      pipelineSuccessResult: 'Example passed. Image-build CI is followed by illustrative local validation; this demo did not run an actual build or deployment.',
      healthChangedConsole: '$ ./health-check.sh\nInputs changed. Run a check to generate a new report.', healthChangedResult: 'Inputs updated. Previous results have been cleared.',
      healthSimulation: '[SIMULATION] Sample inputs; no system access', healthMemory: 'Memory usage', healthDisk: 'Root disk usage', healthService: 'Example service', threshold: 'threshold', active: 'active', inactive: 'inactive',
      warningsFound: n => `${n} warning${n === 1 ? '' : 's'} found`, allPassed: 'All checks passed', exitCode: 'exit code',
      healthWarningPrefix: n => `Example report: ${n} warning${n === 1 ? '' : 's'}. `, investigateDisk: 'Investigate disk usage. ', investigateMemory: 'Investigate memory usage. ', inspectService: 'Inspect service logs and configuration.',
      healthHealthy: 'Example report: all checks are healthy. Exit code 0 can signal success to another script.'
    },
    pl: {
      languageLabel: 'Zmień język', resultCount: n => `Wyświetlane projekty: ${n}`,
      dialogNumber: n => `PROJEKT ${n} / LABORATORIUM`, repoView: 'Zobacz repozytorium GitHub ↗', repoTitle: 'Repozytorium GitHub', repoMissing: 'Link zostanie dodany',
      simulating: 'Symulacja…', pipelineRunning: 'Uruchamianie przykładowego workflow…', waiting: 'Oczekuje', running: 'Uruchamianie…', failed: 'Błąd', skipped: 'Pominięto', passed: 'Zakończono', runAgain: 'Uruchom ponownie ▷',
      pipelineIntro: '$ run-example-workflow\n[SYMULACJA] Wszystkie poniższe dane są przykładowe.\n',
      pipelineLines: ['✓ Pobrano przykładowe repozytorium', '✓ Zbudowano obraz Docker: devops-docker-demo', '✓ Uruchomiono przykładowy kontener na localhost:5000', '✓ Lokalny GET /health → 200 {"status":"ok"}'],
      pipelineFailConsole: '✗ docker build: instalacja zależności nie powiodła się\n— Brak nowego obrazu\n— Uruchomienie kontenera i lokalny health check pominięte\n',
      pipelineFailResult: 'Przykład zakończył się błędem: sprawdź błąd zależności i napraw build przed uruchomieniem kontenera. Nie wykonano wdrożenia.',
      pipelineSuccessResult: 'Przykład zakończony powodzeniem. Po CI budującym obraz pokazano przykładową walidację lokalną; demo nie uruchomiło prawdziwego buildu ani wdrożenia.',
      healthChangedConsole: '$ ./health-check.sh\nDane wejściowe zmienione. Uruchom sprawdzenie, aby wygenerować nowy raport.', healthChangedResult: 'Dane wejściowe zaktualizowane. Poprzednie wyniki zostały wyczyszczone.',
      healthSimulation: '[SYMULACJA] Przykładowe dane; bez dostępu do systemu', healthMemory: 'Użycie pamięci', healthDisk: 'Użycie dysku root', healthService: 'Przykładowa usługa', threshold: 'próg', active: 'aktywna', inactive: 'nieaktywna',
      warningsFound: n => `Liczba ostrzeżeń: ${n}`, allPassed: 'Wszystkie kontrole zakończone pomyślnie', exitCode: 'kod wyjścia',
      healthWarningPrefix: n => `Przykładowy raport: ostrzeżenia — ${n}. `, investigateDisk: 'Sprawdź użycie dysku. ', investigateMemory: 'Sprawdź użycie pamięci. ', inspectService: 'Sprawdź logi i konfigurację usługi.',
      healthHealthy: 'Przykładowy raport: wszystkie kontrole są poprawne. Kod wyjścia 0 może sygnalizować sukces innemu skryptowi.'
    },
    ru: {
      languageLabel: 'Сменить язык', resultCount: n => `Показано проектов: ${n}`,
      dialogNumber: n => `ПРОЕКТ ${n} / УЧЕБНАЯ ЛАБОРАТОРИЯ`, repoView: 'Открыть репозиторий GitHub ↗', repoTitle: 'Репозиторий GitHub', repoMissing: 'Ссылка будет добавлена',
      simulating: 'Симуляция…', pipelineRunning: 'Запуск примера workflow…', waiting: 'Ожидание', running: 'Выполняется…', failed: 'Ошибка', skipped: 'Пропущено', passed: 'Готово', runAgain: 'Запустить ещё раз ▷',
      pipelineIntro: '$ run-example-workflow\n[СИМУЛЯЦИЯ] Все данные ниже приведены для примера.\n',
      pipelineLines: ['✓ Пример репозитория получен', '✓ Docker-образ собран: devops-docker-demo', '✓ Пример контейнера запущен на localhost:5000', '✓ Локальный GET /health → 200 {"status":"ok"}'],
      pipelineFailConsole: '✗ docker build: ошибка установки зависимостей\n— Новый образ не создан\n— Запуск контейнера и локальная health-проверка пропущены\n',
      pipelineFailResult: 'Пример завершился ошибкой: проверьте проблему с зависимостями и исправьте сборку до запуска контейнера. Развёртывание не выполнялось.',
      pipelineSuccessResult: 'Пример завершён успешно. После CI-сборки образа показана отдельная локальная проверка; это демо не выполняло реальную сборку или развёртывание.',
      healthChangedConsole: '$ ./health-check.sh\nВходные данные изменены. Запустите проверку, чтобы создать новый отчёт.', healthChangedResult: 'Входные данные обновлены. Предыдущие результаты очищены.',
      healthSimulation: '[СИМУЛЯЦИЯ] Пример данных; доступа к системе нет', healthMemory: 'Использование памяти', healthDisk: 'Использование корневого диска', healthService: 'Пример сервиса', threshold: 'порог', active: 'активен', inactive: 'неактивен',
      warningsFound: n => `Предупреждений: ${n}`, allPassed: 'Все проверки пройдены', exitCode: 'код выхода',
      healthWarningPrefix: n => `Пример отчёта: предупреждений — ${n}. `, investigateDisk: 'Проверьте использование диска. ', investigateMemory: 'Проверьте использование памяти. ', inspectService: 'Проверьте логи и конфигурацию сервиса.',
      healthHealthy: 'Пример отчёта: все проверки в норме. Код выхода 0 может сообщить другому скрипту об успешном выполнении.'
    },
    uk: {
      languageLabel: 'Змінити мову', resultCount: n => `Показано проєктів: ${n}`,
      dialogNumber: n => `ПРОЄКТ ${n} / НАВЧАЛЬНА ЛАБОРАТОРІЯ`, repoView: 'Відкрити репозиторій GitHub ↗', repoTitle: 'Репозиторій GitHub', repoMissing: 'Посилання буде додано',
      simulating: 'Симуляція…', pipelineRunning: 'Запуск прикладу workflow…', waiting: 'Очікування', running: 'Виконується…', failed: 'Помилка', skipped: 'Пропущено', passed: 'Готово', runAgain: 'Запустити ще раз ▷',
      pipelineIntro: '$ run-example-workflow\n[СИМУЛЯЦІЯ] Усі дані нижче наведені як приклад.\n',
      pipelineLines: ['✓ Приклад репозиторію отримано', '✓ Docker-образ зібрано: devops-docker-demo', '✓ Приклад контейнера запущено на localhost:5000', '✓ Локальний GET /health → 200 {"status":"ok"}'],
      pipelineFailConsole: '✗ docker build: помилка встановлення залежностей\n— Новий образ не створено\n— Запуск контейнера та локальну health-перевірку пропущено\n',
      pipelineFailResult: 'Приклад завершився помилкою: перевірте проблему із залежностями та виправте збірку до запуску контейнера. Розгортання не виконувалося.',
      pipelineSuccessResult: 'Приклад завершено успішно. Після CI-збірки образу показано окрему локальну перевірку; це демо не виконувало реальної збірки чи розгортання.',
      healthChangedConsole: '$ ./health-check.sh\nВхідні дані змінено. Запустіть перевірку, щоб створити новий звіт.', healthChangedResult: 'Вхідні дані оновлено. Попередні результати очищено.',
      healthSimulation: '[СИМУЛЯЦІЯ] Приклад даних; доступу до системи немає', healthMemory: 'Використання пам’яті', healthDisk: 'Використання кореневого диска', healthService: 'Приклад сервісу', threshold: 'поріг', active: 'активний', inactive: 'неактивний',
      warningsFound: n => `Попереджень: ${n}`, allPassed: 'Усі перевірки пройдено', exitCode: 'код виходу',
      healthWarningPrefix: n => `Приклад звіту: попереджень — ${n}. `, investigateDisk: 'Перевірте використання диска. ', investigateMemory: 'Перевірте використання пам’яті. ', inspectService: 'Перевірте логи та конфігурацію сервісу.',
      healthHealthy: 'Приклад звіту: усі перевірки в нормі. Код виходу 0 може повідомити іншому скрипту про успішне виконання.'
    }
  },
  strings: {
    pl: {
      'Skip to content': 'Przejdź do treści',
      'JUNIOR DEVOPS PORTFOLIO': 'PORTFOLIO JUNIOR DEVOPS',
      'Projects': 'Projekty', 'About me': 'O mnie',
      'KRAKÓW, POLAND': 'KRAKÓW, POLSKA', 'OPEN TO JUNIOR ROLES': 'OTWARTY NA ROLE JUNIOR',
      'Small projects.': 'Małe projekty.', 'Solid foundations.': 'Solidne podstawy.',
      'I’m Dmytro, a computer science student and AWS Certified Cloud Practitioner, building toward my first DevOps role.': 'Jestem Dmytro, studiuję informatykę i posiadam certyfikat AWS Certified Cloud Practitioner. Rozwijam się w kierunku pierwszej roli DevOps.',
      'Hands-on with Linux, Docker, Git, and CI. Bringing an operations mindset from my work at Accenture.': 'Praktycznie pracuję z Linuksem, Dockerem, Gitem i CI. Wnoszę operacyjne podejście z pracy w Accenture.',
      'Explore my projects': 'Zobacz moje projekty', 'Let’s connect': 'Skontaktujmy się',
      'AWS CERTIFIED CLOUD PRACTITIONER': 'AWS CERTIFIED CLOUD PRACTITIONER',
      'THE LEARNING LOOP': 'PĘTLA NAUKI', '01 / START SMALL': '01 / ZACZNIJ OD MAŁEGO', 'Code': 'Kod', '02 / MAKE REPEATABLE': '02 / ZRÓB TO POWTARZALNIE', 'Build': 'Build', '04 / UNDERSTAND': '04 / ZROZUM', 'Observe': 'Obserwuj', 'Linux health checks': 'Kontrole stanu Linux', '03 / RUN LOCALLY': '03 / URUCHOM LOKALNIE', 'Run': 'Uruchom', 'Flask container': 'Kontener Flask', 'build. learn. repeat.': 'buduj. ucz się. powtarzaj.', 'progress > perfection': 'postęp > perfekcja',
      'MY LEARNING TOOLKIT': 'MÓJ ZESTAW DO NAUKI', '01 / PROJECT LAB': '01 / LABORATORIUM PROJEKTÓW', 'From concepts to practice': 'Od koncepcji do praktyki',
      'A Docker project with source code, and a Linux practice lab. Explore the implementation and try the demos.': 'Projekt Docker z kodem źródłowym oraz laboratorium praktyczne Linux. Zobacz implementację i wypróbuj dema.',
      '02 FEATURED': '02 WYRÓŻNIONE', 'All projects': 'Wszystkie projekty', 'Containers & CI': 'Kontenery i CI', 'Linux practice': 'Praktyka Linux', 'Showing 2 projects': 'Wyświetlane projekty: 2',
      'DELIVERY WORKFLOW': 'WORKFLOW DOSTARCZANIA', 'ILLUSTRATIVE': 'PRZYKŁADOWE', 'Check': 'Sprawdź', 'Docker image build': 'Budowanie obrazu Docker', 'LEARNING LAB': 'LABORATORIUM',
      'PROJECT 01': 'PROJEKT 01', 'Personal project · code available': 'Projekt własny · kod dostępny', 'Dockerized Python app & CI': 'Aplikacja Python w Dockerze i CI',
      'A Flask service with a /health endpoint, packaged with Docker. GitHub Actions builds the image on pushes and pull requests to main.': 'Usługa Flask z endpointem /health, spakowana w Dockerze. GitHub Actions buduje obraz przy pushach i pull requestach do main.',
      'Explore project': 'Zobacz projekt', 'View source': 'Zobacz kod', 'EXAMPLE OUTPUT': 'PRZYKŁADOWY WYNIK', 'Memory usage': 'Użycie pamięci', 'Disk usage': 'Użycie dysku', 'Service status': 'Status usługi', 'active': 'aktywna', 'All checks passed': 'Wszystkie kontrole zakończone pomyślnie',
      'PROJECT 02': 'PROJEKT 02', 'Hands-on practice': 'Praktyka', 'Linux operations lab': 'Laboratorium operacji Linux',
      'Daily Fedora use, service troubleshooting, and system configuration. An interactive lab shows how memory, disk, and service checks fit together.': 'Codzienna praca z Fedorą, diagnozowanie usług i konfiguracja systemu. Interaktywne laboratorium pokazuje, jak łączą się kontrole pamięci, dysku i usług.',
      'Shell scripting': 'Skrypty shell', 'Interactive learning lab': 'Interaktywne laboratorium',
      'The Docker project links to real source code. All interactive demos use illustrative data; they do not run containers or inspect a live system.': 'Projekt Docker prowadzi do rzeczywistego kodu źródłowego. Wszystkie interaktywne dema używają danych przykładowych; nie uruchamiają kontenerów ani nie sprawdzają prawdziwego systemu.',
      'ADDITIONAL PROJECT / RAG PROTOTYPE': 'DODATKOWY PROJEKT / PROTOTYP RAG', 'Context-aware document assistant': 'Asystent dokumentów uwzględniający kontekst',
      'A Python prototype for PDF question answering: document chunking, vector embeddings, semantic retrieval, and API-based LLM integration.': 'Prototyp w Pythonie do odpowiadania na pytania o PDF: dzielenie dokumentów, embeddingi wektorowe, wyszukiwanie semantyczne i integracja LLM przez API.',
      'Prototype': 'Prototyp', 'Repository not linked': 'Repozytorium niepodłączone',
      '02 / BACKGROUND & SKILLS': '02 / DOŚWIADCZENIE I UMIEJĘTNOŚCI', 'Operations mindset.': 'Podejście operacyjne.', 'DevOps direction.': 'Kierunek DevOps.',
      'I like understanding how systems work—and figuring out what to check when they don’t.': 'Lubię rozumieć, jak działają systemy — i ustalać, co sprawdzić, gdy coś przestaje działać.',
      'My professional experience is in data operations. My DevOps experience comes from personal projects, self-study, and daily Linux practice.': 'Moje doświadczenie zawodowe jest związane z operacjami na danych. Doświadczenie DevOps zdobywam przez projekty własne, samodzielną naukę i codzienną pracę z Linuksem.',
      'CERTIFICATION': 'CERTYFIKAT', '2023 — PRESENT': '2023 — OBECNIE', 'Junior Data Analyst': 'Junior Data Analyst', 'Content, Policy & Operations · Kraków': 'Content, Policy & Operations · Kraków',
      'Investigating issues, maintaining data quality, and escalating operational problems in a high-volume, SLA-driven environment. Working with cross-functional teams under time pressure.': 'Analizowanie problemów, dbanie o jakość danych i eskalowanie problemów operacyjnych w środowisku o dużym wolumenie i pracy według SLA. Współpraca z zespołami międzyfunkcyjnymi pod presją czasu.',
      'EDUCATION': 'EDUKACJA', '2022 — PRESENT': '2022 — OBECNIE', 'Computer Science': 'Informatyka', 'WSZiB Kraków · Bachelor’s degree in progress': 'WSZiB Kraków · studia inżynierskie w toku',
      'Building a foundation in systems, networks, and software while developing practical infrastructure skills through self-study.': 'Buduję podstawy w obszarze systemów, sieci i oprogramowania, jednocześnie rozwijając praktyczne umiejętności infrastrukturalne poprzez samodzielną naukę.',
      'EARLIER EXPERIENCE': 'WCZEŚNIEJSZE DOŚWIADCZENIE', 'Restaurant Assistant Manager · 2014–2023': 'Zastępca kierownika restauracji · 2014–2023', 'Daily operations, staff scheduling, supplier coordination, and team ownership.': 'Codzienne operacje, grafiki pracowników, koordynacja dostawców i odpowiedzialność za zespół.',
      'Used in personal projects or daily work with my own systems.': 'Używane w projektach własnych lub podczas codziennej pracy z moimi systemami.', 'Foundational knowledge': 'Wiedza podstawowa', 'Early hands-on exposure and concepts I’m continuing to develop.': 'Pierwsze doświadczenia praktyczne i zagadnienia, które nadal rozwijam.', 'Networking': 'Sieci komputerowe',
      'How I work': 'Jak pracuję', 'Troubleshooting, clear documentation, ownership, and cross-team communication.': 'Diagnozowanie problemów, jasna dokumentacja, odpowiedzialność i komunikacja między zespołami.', 'English & Polish': 'Angielski i polski', 'Fluent': 'Biegły', 'Ukrainian & Russian': 'Ukraiński i rosyjski', 'Native': 'Ojczysty',
      'Built with curiosity. Kept honest.': 'Zbudowane z ciekawości. Bez przesady.', 'Back to top ↑': 'Wróć na górę ↑', 'Close project details': 'Zamknij szczegóły projektu', 'Project details': 'Szczegóły projektu', 'Overview': 'Przegląd', 'Workflow': 'Przepływ pracy', 'Interactive demo': 'Interaktywne demo', 'GitHub repository': 'Repozytorium GitHub', 'Link to be added': 'Link zostanie dodany', 'Try the demo →': 'Wypróbuj demo →',
      'Enable JavaScript to use project filters, detail views, and interactive demos. Project summaries and background are available above.': 'Włącz JavaScript, aby korzystać z filtrów projektów, widoków szczegółowych i interaktywnych dem. Opisy projektów i informacje o mnie są dostępne powyżej.',
      'The problem': 'Problem', 'A small service needs a repeatable way to run, and a basic check that its Docker image can still build after a change.': 'Mała usługa potrzebuje powtarzalnego sposobu uruchamiania oraz podstawowej kontroli, czy po zmianie nadal można zbudować jej obraz Docker.', 'What I built': 'Co zbudowałem', 'A Flask application with a homepage and a JSON health endpoint, plus a Dockerfile and a GitHub Actions workflow for image builds.': 'Aplikację Flask ze stroną główną i endpointem JSON health, wraz z Dockerfile i workflow GitHub Actions budującym obraz.', 'In the repository': 'W repozytorium',
      'app.py: / and /health routes.': 'app.py: trasy / i /health.', 'Dockerfile: Python base image, dependencies, and startup command.': 'Dockerfile: bazowy obraz Python, zależności i komenda startowa.', 'Port 5000 exposed for the local service.': 'Port 5000 udostępniony dla usługi lokalnej.', 'CI builds on pushes and pull requests to main.': 'CI buduje obraz przy pushach i pull requestach do main.', 'A README with Docker commands and endpoint examples.': 'README z komendami Docker i przykładami endpointów.',
      'Container basics': 'Podstawy kontenerów', 'Build automation': 'Automatyzacja buildu', 'Version control': 'Kontrola wersji', 'Current scope:': 'Obecny zakres:', 'a personal learning project. The configured CI checks that the image builds; it does not currently run a unit-test suite or deploy to production. The interactive demo is a simulation.': 'osobisty projekt edukacyjny. Skonfigurowane CI sprawdza, czy obraz się buduje; obecnie nie uruchamia zestawu testów jednostkowych ani nie wdraża na produkcję. Interaktywne demo jest symulacją.',
      'The first path reflects the repository’s CI configuration. The second shows how to run and check the service locally.': 'Pierwsza ścieżka odzwierciedla konfigurację CI w repozytorium. Druga pokazuje, jak uruchomić i sprawdzić usługę lokalnie.', '01 / IMPLEMENTED CI WORKFLOW': '01 / ZAIMPLEMENTOWANY WORKFLOW CI', 'Push or PR': 'Push lub PR', 'main branch': 'gałąź main', 'Checkout': 'Checkout', 'Build image': 'Zbuduj obraz', 'docker build': 'docker build', '02 / LOCAL VALIDATION': '02 / WALIDACJA LOKALNA', 'Run container': 'Uruchom kontener', 'Port 5000': 'Port 5000', 'JSON response': 'Odpowiedź JSON', 'status: ok': 'status: ok', 'Next improvements:': 'Kolejne ulepszenia:', 'endpoint tests, dependency checks, and a production-ready server configuration. Automatic deployment is outside the current project scope.': 'testy endpointów, kontrole zależności i konfiguracja serwera gotowa do produkcji. Automatyczne wdrażanie jest poza obecnym zakresem projektu.',
      'Browser simulation with sample data. No real CI job, container, or server is running.': 'Symulacja w przeglądarce z przykładowymi danymi. Nie działa żaden prawdziwy job CI, kontener ani serwer.', 'Try an image build': 'Wypróbuj budowanie obrazu', 'Successful image build': 'Udane budowanie obrazu', 'Dependency installation fails': 'Błąd instalacji zależności', 'Run simulation': 'Uruchom symulację', 'Simulated pipeline stages': 'Symulowane etapy pipeline', 'Ready': 'Gotowe', 'Start container': 'Uruchom kontener', 'Health check': 'Kontrola stanu', 'Simulated pipeline output': 'Symulowany wynik pipeline', 'Choose a scenario, then run the simulation.': 'Wybierz scenariusz, a następnie uruchom symulację.', 'The first two steps represent CI; the last two illustrate separate local validation.': 'Pierwsze dwa kroki przedstawiają CI; dwa ostatnie pokazują osobną walidację lokalną.', 'Personal project · source code available': 'Projekt własny · kod źródłowy dostępny',
      'My Linux practice': 'Moja praktyka z Linuksem', 'I use Fedora daily and work with command-line configuration, package management, services, processes, and system settings.': 'Na co dzień używam Fedory i pracuję z konfiguracją w terminalu, zarządzaniem pakietami, usługami, procesami i ustawieniami systemowymi.', 'The learning lab': 'Laboratorium edukacyjne', 'This interactive example turns three signals—memory, disk space, and a service state—into a readable status report.': 'Ten interaktywny przykład zamienia trzy sygnały — pamięć, miejsce na dysku i stan usługi — w czytelny raport.', 'What I’m practicing': 'Co ćwiczę', 'Investigating system and service behavior.': 'Analizowanie zachowania systemu i usług.', 'Reading memory and disk usage.': 'Odczytywanie użycia pamięci i dysku.', 'Understanding systemd service status.': 'Rozumienie statusu usług systemd.', 'Using Bash to make repeatable checks.': 'Używanie Basha do powtarzalnych kontroli.', 'Interpreting exit codes and documenting findings.': 'Interpretowanie kodów wyjścia i dokumentowanie wyników.', 'Linux administration': 'Administracja Linux', 'Service troubleshooting': 'Diagnozowanie usług', 'Automation fundamentals': 'Podstawy automatyzacji', 'Demo scope:': 'Zakres dema:', 'the health-check tool uses sample inputs in this browser. A standalone health-check script has not been linked, and no real machine is inspected or changed.': 'narzędzie health-check korzysta w przeglądarce z przykładowych danych. Nie podłączono samodzielnego skryptu health-check, a żadna prawdziwa maszyna nie jest sprawdzana ani modyfikowana.',
      'Proposed workflow for a Linux machine using systemd. These checks are a small learning exercise, not a complete monitoring system.': 'Proponowany workflow dla maszyny Linux z systemd. Te kontrole są małym ćwiczeniem edukacyjnym, a nie pełnym systemem monitoringu.', '01 / COLLECT LOCAL SIGNALS': '01 / ZBIERZ LOKALNE SYGNAŁY', 'Memory': 'Pamięć', 'Root disk': 'Dysk root', 'Service': 'Usługa', '02 / EVALUATE & REPORT': '02 / OCEŃ I RAPORTUJ', 'Bash script': 'Skrypt Bash', 'Parse values': 'Parsowanie wartości', 'Check rules': 'Reguły kontroli', 'Thresholds': 'Progi', 'Status report': 'Raport statusu', 'Exit 0 or 1': 'Wyjście 0 lub 1', 'Demo rules:': 'Reguły dema:', 'warn when memory or disk usage is at least 80%, or when the example service is inactive. A production-ready script would also handle command errors and missing services explicitly.': 'ostrzeżenie, gdy użycie pamięci lub dysku wynosi co najmniej 80% albo gdy przykładowa usługa jest nieaktywna. Skrypt produkcyjny powinien również jawnie obsługiwać błędy poleceń i brakujące usługi.',
      'Illustrative inputs only. This demo does not inspect or change any real machine.': 'Wyłącznie dane przykładowe. To demo nie sprawdza ani nie zmienia żadnej prawdziwej maszyny.', 'Sample scenario': 'Przykładowy scenariusz', 'Healthy machine': 'System w normie', 'Disk pressure': 'Wysokie użycie dysku', 'Service stopped': 'Usługa zatrzymana', 'Custom inputs': 'Własne dane', 'Run health check': 'Uruchom health check', 'Warning at ≥ 80%': 'Ostrzeżenie od ≥ 80%', 'Example service is active': 'Przykładowa usługa jest aktywna', 'Change inputs, then run a check': 'Zmień dane, potem uruchom kontrolę', 'Simulated health check output': 'Symulowany wynik health check', 'Sample inputs ready. Run a check to generate the report.': 'Przykładowe dane gotowe. Uruchom kontrolę, aby wygenerować raport.', 'Healthy: exit 0. Any warning: exit 1.': 'W normie: exit 0. Dowolne ostrzeżenie: exit 1.', 'Hands-on practice · simulated health check': 'Praktyka · symulowany health check',
      'Filter projects': 'Filtruj projekty', 'Main navigation': 'Główna nawigacja', 'Dmytro Poliakov, home': 'Dmytro Poliakov, strona główna', 'Illustrative workflow: code, build, run, observe. A learning loop, not a live deployment.': 'Przykładowy workflow: kod, build, uruchomienie, obserwacja. Pętla nauki, a nie działające wdrożenie.', 'Code to build to run to health check': 'Od kodu przez build i uruchomienie do health check'
    },
    ru: {
      'Skip to content': 'Перейти к содержимому', 'JUNIOR DEVOPS PORTFOLIO': 'ПОРТФОЛИО JUNIOR DEVOPS', 'Projects': 'Проекты', 'About me': 'Обо мне',
      'KRAKÓW, POLAND': 'КРАКОВ, ПОЛЬША', 'OPEN TO JUNIOR ROLES': 'ОТКРЫТ К JUNIOR-ПОЗИЦИЯМ', 'Small projects.': 'Небольшие проекты.', 'Solid foundations.': 'Крепкая основа.',
      'I’m Dmytro, a computer science student and AWS Certified Cloud Practitioner, building toward my first DevOps role.': 'Я Dmytro, студент информатики и AWS Certified Cloud Practitioner. Развиваюсь, чтобы получить свою первую роль в DevOps.',
      'Hands-on with Linux, Docker, Git, and CI. Bringing an operations mindset from my work at Accenture.': 'Практикую Linux, Docker, Git и CI. Переношу в DevOps операционный подход из работы в Accenture.',
      'Explore my projects': 'Посмотреть проекты', 'Let’s connect': 'Связаться со мной', 'THE LEARNING LOOP': 'ЦИКЛ ОБУЧЕНИЯ', '01 / START SMALL': '01 / НАЧНИ С МАЛОГО', 'Code': 'Код', '02 / MAKE REPEATABLE': '02 / СДЕЛАЙ ПОВТОРЯЕМЫМ', 'Build': 'Сборка', '04 / UNDERSTAND': '04 / ПОЙМИ', 'Observe': 'Наблюдение', 'Linux health checks': 'Проверки состояния Linux', '03 / RUN LOCALLY': '03 / ЗАПУСТИ ЛОКАЛЬНО', 'Run': 'Запуск', 'Flask container': 'Контейнер Flask', 'build. learn. repeat.': 'собирай. учись. повторяй.', 'progress > perfection': 'прогресс > идеал',
      'MY LEARNING TOOLKIT': 'МОЙ НАБОР ДЛЯ ОБУЧЕНИЯ', '01 / PROJECT LAB': '01 / ЛАБОРАТОРИЯ ПРОЕКТОВ', 'From concepts to practice': 'От теории к практике', 'A Docker project with source code, and a Linux practice lab. Explore the implementation and try the demos.': 'Проект Docker с исходным кодом и практическая лаборатория Linux. Посмотрите реализацию и попробуйте демо.', '02 FEATURED': '02 ИЗБРАННЫХ', 'All projects': 'Все проекты', 'Containers & CI': 'Контейнеры и CI', 'Linux practice': 'Практика Linux', 'Showing 2 projects': 'Показано проектов: 2',
      'DELIVERY WORKFLOW': 'WORKFLOW ДОСТАВКИ', 'ILLUSTRATIVE': 'ПРИМЕР', 'Check': 'Проверка', 'Docker image build': 'Сборка Docker-образа', 'LEARNING LAB': 'УЧЕБНАЯ ЛАБОРАТОРИЯ', 'PROJECT 01': 'ПРОЕКТ 01', 'Personal project · code available': 'Личный проект · код доступен', 'Dockerized Python app & CI': 'Python-приложение в Docker и CI', 'A Flask service with a /health endpoint, packaged with Docker. GitHub Actions builds the image on pushes and pull requests to main.': 'Flask-сервис с endpoint /health, упакованный в Docker. GitHub Actions собирает образ при push и pull request в main.', 'Explore project': 'Открыть проект', 'View source': 'Исходный код', 'EXAMPLE OUTPUT': 'ПРИМЕР ВЫВОДА', 'Memory usage': 'Использование памяти', 'Disk usage': 'Использование диска', 'Service status': 'Статус сервиса', 'active': 'активен', 'All checks passed': 'Все проверки пройдены',
      'PROJECT 02': 'ПРОЕКТ 02', 'Hands-on practice': 'Практика', 'Linux operations lab': 'Лаборатория Linux-операций', 'Daily Fedora use, service troubleshooting, and system configuration. An interactive lab shows how memory, disk, and service checks fit together.': 'Ежедневная работа в Fedora, диагностика сервисов и настройка системы. Интерактивная лаборатория показывает, как связаны проверки памяти, диска и сервисов.', 'Shell scripting': 'Shell-скрипты', 'Interactive learning lab': 'Интерактивная лаборатория', 'The Docker project links to real source code. All interactive demos use illustrative data; they do not run containers or inspect a live system.': 'Проект Docker содержит ссылку на реальный исходный код. Все интерактивные демо используют примерные данные; они не запускают контейнеры и не проверяют живую систему.',
      'ADDITIONAL PROJECT / RAG PROTOTYPE': 'ДОПОЛНИТЕЛЬНЫЙ ПРОЕКТ / ПРОТОТИП RAG', 'Context-aware document assistant': 'Контекстный ассистент по документам', 'A Python prototype for PDF question answering: document chunking, vector embeddings, semantic retrieval, and API-based LLM integration.': 'Прототип на Python для ответов на вопросы по PDF: разбиение документов, векторные embeddings, семантический поиск и интеграция LLM через API.', 'Prototype': 'Прототип', 'Repository not linked': 'Репозиторий не подключён',
      '02 / BACKGROUND & SKILLS': '02 / ОПЫТ И НАВЫКИ', 'Operations mindset.': 'Операционный подход.', 'DevOps direction.': 'Направление DevOps.', 'I like understanding how systems work—and figuring out what to check when they don’t.': 'Мне нравится понимать, как работают системы, и разбираться, что проверять, когда что-то перестаёт работать.', 'My professional experience is in data operations. My DevOps experience comes from personal projects, self-study, and daily Linux practice.': 'Мой профессиональный опыт связан с операционной работой с данными. Опыт DevOps я получаю через личные проекты, самостоятельное обучение и ежедневную практику Linux.', 'CERTIFICATION': 'СЕРТИФИКАЦИЯ', '2023 — PRESENT': '2023 — НАСТОЯЩЕЕ ВРЕМЯ', 'Investigating issues, maintaining data quality, and escalating operational problems in a high-volume, SLA-driven environment. Working with cross-functional teams under time pressure.': 'Исследую проблемы, поддерживаю качество данных и эскалирую операционные инциденты в среде с большим объёмом задач и SLA. Работаю с кросс-функциональными командами в условиях ограниченного времени.',
      'EDUCATION': 'ОБРАЗОВАНИЕ', '2022 — PRESENT': '2022 — НАСТОЯЩЕЕ ВРЕМЯ', 'Computer Science': 'Информатика', 'WSZiB Kraków · Bachelor’s degree in progress': 'WSZiB Kraków · бакалавриат в процессе', 'Building a foundation in systems, networks, and software while developing practical infrastructure skills through self-study.': 'Формирую базу в системах, сетях и разработке, параллельно развивая практические инфраструктурные навыки самостоятельно.', 'EARLIER EXPERIENCE': 'ПРЕДЫДУЩИЙ ОПЫТ', 'Restaurant Assistant Manager · 2014–2023': 'Заместитель менеджера ресторана · 2014–2023', 'Daily operations, staff scheduling, supplier coordination, and team ownership.': 'Ежедневные операции, составление графиков, координация поставщиков и ответственность за команду.',
      'Hands-on practice': 'Практические навыки', 'Used in personal projects or daily work with my own systems.': 'Использую в личных проектах или в ежедневной работе со своими системами.', 'Foundational knowledge': 'Базовые знания', 'Early hands-on exposure and concepts I’m continuing to develop.': 'Начальный практический опыт и темы, которые продолжаю развивать.', 'Networking': 'Компьютерные сети', 'How I work': 'Как я работаю', 'Troubleshooting, clear documentation, ownership, and cross-team communication.': 'Диагностика проблем, понятная документация, ответственность и коммуникация между командами.', 'English & Polish': 'Английский и польский', 'Fluent': 'Свободно', 'Ukrainian & Russian': 'Украинский и русский', 'Native': 'Родные',
      'Built with curiosity. Kept honest.': 'Сделано с любопытством. Без преувеличений.', 'Back to top ↑': 'Наверх ↑', 'Close project details': 'Закрыть детали проекта', 'Project details': 'Детали проекта', 'Overview': 'Обзор', 'Workflow': 'Workflow', 'Interactive demo': 'Интерактивное демо', 'GitHub repository': 'Репозиторий GitHub', 'Link to be added': 'Ссылка будет добавлена', 'Try the demo →': 'Попробовать демо →', 'Enable JavaScript to use project filters, detail views, and interactive demos. Project summaries and background are available above.': 'Включите JavaScript, чтобы использовать фильтры проектов, подробные страницы и интерактивные демо. Краткие описания проектов и информация обо мне доступны выше.',
      'The problem': 'Задача', 'A small service needs a repeatable way to run, and a basic check that its Docker image can still build after a change.': 'Небольшому сервису нужен повторяемый способ запуска и базовая проверка того, что после изменений его Docker-образ всё ещё собирается.', 'What I built': 'Что я сделал', 'A Flask application with a homepage and a JSON health endpoint, plus a Dockerfile and a GitHub Actions workflow for image builds.': 'Flask-приложение с главной страницей и JSON health-endpoint, а также Dockerfile и workflow GitHub Actions для сборки образа.', 'In the repository': 'В репозитории', 'app.py: / and /health routes.': 'app.py: маршруты / и /health.', 'Dockerfile: Python base image, dependencies, and startup command.': 'Dockerfile: базовый Python-образ, зависимости и команда запуска.', 'Port 5000 exposed for the local service.': 'Порт 5000 открыт для локального сервиса.', 'CI builds on pushes and pull requests to main.': 'CI запускает сборку при push и pull request в main.', 'A README with Docker commands and endpoint examples.': 'README с Docker-командами и примерами endpoint.', 'Container basics': 'Основы контейнеров', 'Build automation': 'Автоматизация сборки', 'Version control': 'Контроль версий', 'Current scope:': 'Текущий объём:', 'a personal learning project. The configured CI checks that the image builds; it does not currently run a unit-test suite or deploy to production. The interactive demo is a simulation.': 'личный учебный проект. Настроенный CI проверяет, что образ собирается; сейчас он не запускает набор unit-тестов и не разворачивает приложение в production. Интерактивное демо — симуляция.',
      'The first path reflects the repository’s CI configuration. The second shows how to run and check the service locally.': 'Первый путь отражает CI-конфигурацию репозитория. Второй показывает, как запустить и проверить сервис локально.', '01 / IMPLEMENTED CI WORKFLOW': '01 / РЕАЛИЗОВАННЫЙ CI WORKFLOW', 'Push or PR': 'Push или PR', 'main branch': 'ветка main', 'Checkout': 'Checkout', 'Build image': 'Сборка образа', '02 / LOCAL VALIDATION': '02 / ЛОКАЛЬНАЯ ПРОВЕРКА', 'Run container': 'Запуск контейнера', 'JSON response': 'JSON-ответ', 'Next improvements:': 'Следующие улучшения:', 'endpoint tests, dependency checks, and a production-ready server configuration. Automatic deployment is outside the current project scope.': 'тесты endpoint, проверки зависимостей и production-ready конфигурация сервера. Автоматическое развёртывание не входит в текущий объём проекта.', 'Browser simulation with sample data. No real CI job, container, or server is running.': 'Симуляция в браузере с примерными данными. Реальные CI job, контейнер или сервер не запускаются.', 'Try an image build': 'Попробовать сборку образа', 'Successful image build': 'Успешная сборка образа', 'Dependency installation fails': 'Ошибка установки зависимостей', 'Run simulation': 'Запустить симуляцию', 'Simulated pipeline stages': 'Симулированные этапы pipeline', 'Ready': 'Готово', 'Start container': 'Запуск контейнера', 'Health check': 'Health check', 'Simulated pipeline output': 'Симулированный вывод pipeline', 'Choose a scenario, then run the simulation.': 'Выберите сценарий и запустите симуляцию.', 'The first two steps represent CI; the last two illustrate separate local validation.': 'Первые два шага представляют CI, последние два показывают отдельную локальную проверку.', 'Personal project · source code available': 'Личный проект · исходный код доступен',
      'My Linux practice': 'Моя практика Linux', 'I use Fedora daily and work with command-line configuration, package management, services, processes, and system settings.': 'Я ежедневно использую Fedora и работаю с настройкой через командную строку, пакетами, сервисами, процессами и системными параметрами.', 'The learning lab': 'Учебная лаборатория', 'This interactive example turns three signals—memory, disk space, and a service state—into a readable status report.': 'Этот интерактивный пример превращает три сигнала — память, место на диске и состояние сервиса — в понятный отчёт.', 'What I’m practicing': 'Что я практикую', 'Investigating system and service behavior.': 'Исследование поведения системы и сервисов.', 'Reading memory and disk usage.': 'Анализ использования памяти и диска.', 'Understanding systemd service status.': 'Понимание статусов сервисов systemd.', 'Using Bash to make repeatable checks.': 'Использование Bash для повторяемых проверок.', 'Interpreting exit codes and documenting findings.': 'Интерпретация кодов выхода и документирование результатов.', 'Linux administration': 'Администрирование Linux', 'Service troubleshooting': 'Диагностика сервисов', 'Automation fundamentals': 'Основы автоматизации', 'Demo scope:': 'Объём демо:', 'the health-check tool uses sample inputs in this browser. A standalone health-check script has not been linked, and no real machine is inspected or changed.': 'health-check использует в браузере примерные входные данные. Отдельный скрипт health-check не подключён, реальная машина не проверяется и не изменяется.', 'Proposed workflow for a Linux machine using systemd. These checks are a small learning exercise, not a complete monitoring system.': 'Предлагаемый workflow для Linux-машины с systemd. Эти проверки — небольшое учебное упражнение, а не полноценная система мониторинга.', '01 / COLLECT LOCAL SIGNALS': '01 / СОБРАТЬ ЛОКАЛЬНЫЕ СИГНАЛЫ', 'Memory': 'Память', 'Root disk': 'Корневой диск', 'Service': 'Сервис', '02 / EVALUATE & REPORT': '02 / ОЦЕНИТЬ И СОЗДАТЬ ОТЧЁТ', 'Bash script': 'Bash-скрипт', 'Parse values': 'Разбор значений', 'Check rules': 'Правила проверки', 'Thresholds': 'Пороги', 'Status report': 'Отчёт о состоянии', 'Exit 0 or 1': 'Выход 0 или 1', 'Demo rules:': 'Правила демо:', 'warn when memory or disk usage is at least 80%, or when the example service is inactive. A production-ready script would also handle command errors and missing services explicitly.': 'предупреждать, если использование памяти или диска не ниже 80%, либо если пример сервиса неактивен. Production-ready скрипт также должен явно обрабатывать ошибки команд и отсутствие сервисов.',
      'Illustrative inputs only. This demo does not inspect or change any real machine.': 'Только примерные входные данные. Демо не проверяет и не изменяет реальную машину.', 'Sample scenario': 'Пример сценария', 'Healthy machine': 'Система в норме', 'Disk pressure': 'Высокая нагрузка на диск', 'Service stopped': 'Сервис остановлен', 'Custom inputs': 'Свои данные', 'Run health check': 'Запустить health check', 'Warning at ≥ 80%': 'Предупреждение при ≥ 80%', 'Example service is active': 'Пример сервиса активен', 'Change inputs, then run a check': 'Измените данные и запустите проверку', 'Simulated health check output': 'Симулированный вывод health check', 'Sample inputs ready. Run a check to generate the report.': 'Примерные данные готовы. Запустите проверку для создания отчёта.', 'Healthy: exit 0. Any warning: exit 1.': 'В норме: exit 0. Любое предупреждение: exit 1.', 'Hands-on practice · simulated health check': 'Практика · симулированный health check',
      'Filter projects': 'Фильтр проектов', 'Main navigation': 'Основная навигация', 'Dmytro Poliakov, home': 'Dmytro Poliakov, главная', 'Illustrative workflow: code, build, run, observe. A learning loop, not a live deployment.': 'Пример workflow: код, сборка, запуск, наблюдение. Это цикл обучения, а не живое развёртывание.', 'Code to build to run to health check': 'От кода через сборку и запуск к health check'
    },
    uk: {
      'Skip to content': 'Перейти до вмісту', 'JUNIOR DEVOPS PORTFOLIO': 'ПОРТФОЛІО JUNIOR DEVOPS', 'Projects': 'Проєкти', 'About me': 'Про мене',
      'KRAKÓW, POLAND': 'КРАКІВ, ПОЛЬЩА', 'OPEN TO JUNIOR ROLES': 'ВІДКРИТИЙ ДО JUNIOR-ПОЗИЦІЙ', 'Small projects.': 'Невеликі проєкти.', 'Solid foundations.': 'Міцна основа.',
      'I’m Dmytro, a computer science student and AWS Certified Cloud Practitioner, building toward my first DevOps role.': 'Я Dmytro, студент інформатики та AWS Certified Cloud Practitioner. Розвиваюся, щоб отримати свою першу роль у DevOps.',
      'Hands-on with Linux, Docker, Git, and CI. Bringing an operations mindset from my work at Accenture.': 'Практикую Linux, Docker, Git і CI. Переношу в DevOps операційний підхід із роботи в Accenture.',
      'Explore my projects': 'Переглянути проєкти', 'Let’s connect': 'Зв’язатися зі мною', 'THE LEARNING LOOP': 'ЦИКЛ НАВЧАННЯ', '01 / START SMALL': '01 / ПОЧНИ З МАЛОГО', 'Code': 'Код', '02 / MAKE REPEATABLE': '02 / ЗРОБИ ПОВТОРЮВАНИМ', 'Build': 'Збірка', '04 / UNDERSTAND': '04 / ЗРОЗУМІЙ', 'Observe': 'Спостереження', 'Linux health checks': 'Перевірки стану Linux', '03 / RUN LOCALLY': '03 / ЗАПУСТИ ЛОКАЛЬНО', 'Run': 'Запуск', 'Flask container': 'Контейнер Flask', 'build. learn. repeat.': 'збирай. навчайся. повторюй.', 'progress > perfection': 'прогрес > ідеал',
      'MY LEARNING TOOLKIT': 'МІЙ НАБІР ДЛЯ НАВЧАННЯ', '01 / PROJECT LAB': '01 / ЛАБОРАТОРІЯ ПРОЄКТІВ', 'From concepts to practice': 'Від концепцій до практики', 'A Docker project with source code, and a Linux practice lab. Explore the implementation and try the demos.': 'Docker-проєкт із вихідним кодом та практична лабораторія Linux. Перегляньте реалізацію й спробуйте демо.', '02 FEATURED': '02 ВИБРАНІ', 'All projects': 'Усі проєкти', 'Containers & CI': 'Контейнери та CI', 'Linux practice': 'Практика Linux', 'Showing 2 projects': 'Показано проєктів: 2',
      'DELIVERY WORKFLOW': 'WORKFLOW ДОСТАВКИ', 'ILLUSTRATIVE': 'ПРИКЛАД', 'Check': 'Перевірка', 'Docker image build': 'Збірка Docker-образу', 'LEARNING LAB': 'НАВЧАЛЬНА ЛАБОРАТОРІЯ', 'PROJECT 01': 'ПРОЄКТ 01', 'Personal project · code available': 'Особистий проєкт · код доступний', 'Dockerized Python app & CI': 'Python-застосунок у Docker та CI', 'A Flask service with a /health endpoint, packaged with Docker. GitHub Actions builds the image on pushes and pull requests to main.': 'Flask-сервіс з endpoint /health, упакований у Docker. GitHub Actions збирає образ під час push і pull request до main.', 'Explore project': 'Відкрити проєкт', 'View source': 'Вихідний код', 'EXAMPLE OUTPUT': 'ПРИКЛАД ВИВОДУ', 'Memory usage': 'Використання пам’яті', 'Disk usage': 'Використання диска', 'Service status': 'Статус сервісу', 'active': 'активний', 'All checks passed': 'Усі перевірки пройдено',
      'PROJECT 02': 'ПРОЄКТ 02', 'Hands-on practice': 'Практика', 'Linux operations lab': 'Лабораторія Linux-операцій', 'Daily Fedora use, service troubleshooting, and system configuration. An interactive lab shows how memory, disk, and service checks fit together.': 'Щоденна робота у Fedora, діагностика сервісів і налаштування системи. Інтерактивна лабораторія показує, як поєднуються перевірки пам’яті, диска та сервісів.', 'Shell scripting': 'Shell-скрипти', 'Interactive learning lab': 'Інтерактивна лабораторія', 'The Docker project links to real source code. All interactive demos use illustrative data; they do not run containers or inspect a live system.': 'Docker-проєкт містить посилання на реальний вихідний код. Усі інтерактивні демо використовують прикладні дані; вони не запускають контейнери й не перевіряють живу систему.',
      'ADDITIONAL PROJECT / RAG PROTOTYPE': 'ДОДАТКОВИЙ ПРОЄКТ / ПРОТОТИП RAG', 'Context-aware document assistant': 'Контекстний асистент для документів', 'A Python prototype for PDF question answering: document chunking, vector embeddings, semantic retrieval, and API-based LLM integration.': 'Прототип на Python для відповідей на запитання щодо PDF: поділ документів, векторні embeddings, семантичний пошук та інтеграція LLM через API.', 'Prototype': 'Прототип', 'Repository not linked': 'Репозиторій не підключено',
      '02 / BACKGROUND & SKILLS': '02 / ДОСВІД І НАВИЧКИ', 'Operations mindset.': 'Операційний підхід.', 'DevOps direction.': 'Напрям DevOps.', 'I like understanding how systems work—and figuring out what to check when they don’t.': 'Мені подобається розуміти, як працюють системи, і з’ясовувати, що перевіряти, коли щось перестає працювати.', 'My professional experience is in data operations. My DevOps experience comes from personal projects, self-study, and daily Linux practice.': 'Мій професійний досвід пов’язаний з операційною роботою з даними. Досвід DevOps я здобуваю через особисті проєкти, самостійне навчання та щоденну практику Linux.', 'CERTIFICATION': 'СЕРТИФІКАЦІЯ', '2023 — PRESENT': '2023 — ДОТЕПЕР', 'Investigating issues, maintaining data quality, and escalating operational problems in a high-volume, SLA-driven environment. Working with cross-functional teams under time pressure.': 'Досліджую проблеми, підтримую якість даних та ескалую операційні інциденти в середовищі з великим обсягом задач і SLA. Працюю з кросфункціональними командами в умовах обмеженого часу.',
      'EDUCATION': 'ОСВІТА', '2022 — PRESENT': '2022 — ДОТЕПЕР', 'Computer Science': 'Інформатика', 'WSZiB Kraków · Bachelor’s degree in progress': 'WSZiB Kraków · бакалаврат у процесі', 'Building a foundation in systems, networks, and software while developing practical infrastructure skills through self-study.': 'Формую базу в системах, мережах і програмному забезпеченні, паралельно розвиваючи практичні інфраструктурні навички самостійно.', 'EARLIER EXPERIENCE': 'ПОПЕРЕДНІЙ ДОСВІД', 'Restaurant Assistant Manager · 2014–2023': 'Заступник менеджера ресторану · 2014–2023', 'Daily operations, staff scheduling, supplier coordination, and team ownership.': 'Щоденні операції, складання графіків, координація постачальників і відповідальність за команду.',
      'Hands-on practice': 'Практичні навички', 'Used in personal projects or daily work with my own systems.': 'Використовую в особистих проєктах або щоденній роботі зі своїми системами.', 'Foundational knowledge': 'Базові знання', 'Early hands-on exposure and concepts I’m continuing to develop.': 'Початковий практичний досвід і теми, які продовжую розвивати.', 'Networking': 'Комп’ютерні мережі', 'How I work': 'Як я працюю', 'Troubleshooting, clear documentation, ownership, and cross-team communication.': 'Діагностика проблем, зрозуміла документація, відповідальність і комунікація між командами.', 'English & Polish': 'Англійська та польська', 'Fluent': 'Вільно', 'Ukrainian & Russian': 'Українська та російська', 'Native': 'Рідні',
      'Built with curiosity. Kept honest.': 'Зроблено з цікавістю. Без перебільшень.', 'Back to top ↑': 'Нагору ↑', 'Close project details': 'Закрити деталі проєкту', 'Project details': 'Деталі проєкту', 'Overview': 'Огляд', 'Workflow': 'Workflow', 'Interactive demo': 'Інтерактивне демо', 'GitHub repository': 'Репозиторій GitHub', 'Link to be added': 'Посилання буде додано', 'Try the demo →': 'Спробувати демо →', 'Enable JavaScript to use project filters, detail views, and interactive demos. Project summaries and background are available above.': 'Увімкніть JavaScript, щоб користуватися фільтрами проєктів, детальними переглядами та інтерактивними демо. Описи проєктів та інформація про мене доступні вище.',
      'The problem': 'Завдання', 'A small service needs a repeatable way to run, and a basic check that its Docker image can still build after a change.': 'Невеликому сервісу потрібен повторюваний спосіб запуску та базова перевірка того, що після змін його Docker-образ усе ще збирається.', 'What I built': 'Що я зробив', 'A Flask application with a homepage and a JSON health endpoint, plus a Dockerfile and a GitHub Actions workflow for image builds.': 'Flask-застосунок із головною сторінкою та JSON health-endpoint, а також Dockerfile і workflow GitHub Actions для збірки образу.', 'In the repository': 'У репозиторії', 'app.py: / and /health routes.': 'app.py: маршрути / та /health.', 'Dockerfile: Python base image, dependencies, and startup command.': 'Dockerfile: базовий Python-образ, залежності й команда запуску.', 'Port 5000 exposed for the local service.': 'Порт 5000 відкрито для локального сервісу.', 'CI builds on pushes and pull requests to main.': 'CI запускає збірку під час push і pull request до main.', 'A README with Docker commands and endpoint examples.': 'README з Docker-командами та прикладами endpoint.', 'Container basics': 'Основи контейнерів', 'Build automation': 'Автоматизація збірки', 'Version control': 'Контроль версій', 'Current scope:': 'Поточний обсяг:', 'a personal learning project. The configured CI checks that the image builds; it does not currently run a unit-test suite or deploy to production. The interactive demo is a simulation.': 'особистий навчальний проєкт. Налаштований CI перевіряє, що образ збирається; зараз він не запускає набір unit-тестів і не розгортає застосунок у production. Інтерактивне демо — симуляція.',
      'The first path reflects the repository’s CI configuration. The second shows how to run and check the service locally.': 'Перший шлях відображає CI-конфігурацію репозиторію. Другий показує, як запустити й перевірити сервіс локально.', '01 / IMPLEMENTED CI WORKFLOW': '01 / РЕАЛІЗОВАНИЙ CI WORKFLOW', 'Push or PR': 'Push або PR', 'main branch': 'гілка main', 'Checkout': 'Checkout', 'Build image': 'Збірка образу', '02 / LOCAL VALIDATION': '02 / ЛОКАЛЬНА ПЕРЕВІРКА', 'Run container': 'Запуск контейнера', 'JSON response': 'JSON-відповідь', 'Next improvements:': 'Наступні покращення:', 'endpoint tests, dependency checks, and a production-ready server configuration. Automatic deployment is outside the current project scope.': 'тести endpoint, перевірки залежностей і production-ready конфігурація сервера. Автоматичне розгортання не входить до поточного обсягу проєкту.', 'Browser simulation with sample data. No real CI job, container, or server is running.': 'Симуляція в браузері з прикладними даними. Реальні CI job, контейнер або сервер не запускаються.', 'Try an image build': 'Спробувати збірку образу', 'Successful image build': 'Успішна збірка образу', 'Dependency installation fails': 'Помилка встановлення залежностей', 'Run simulation': 'Запустити симуляцію', 'Simulated pipeline stages': 'Симульовані етапи pipeline', 'Ready': 'Готово', 'Start container': 'Запуск контейнера', 'Health check': 'Health check', 'Simulated pipeline output': 'Симульований вивід pipeline', 'Choose a scenario, then run the simulation.': 'Виберіть сценарій і запустіть симуляцію.', 'The first two steps represent CI; the last two illustrate separate local validation.': 'Перші два кроки представляють CI, останні два показують окрему локальну перевірку.', 'Personal project · source code available': 'Особистий проєкт · вихідний код доступний',
      'My Linux practice': 'Моя практика Linux', 'I use Fedora daily and work with command-line configuration, package management, services, processes, and system settings.': 'Я щодня використовую Fedora та працюю з налаштуваннями через командний рядок, пакетами, сервісами, процесами й системними параметрами.', 'The learning lab': 'Навчальна лабораторія', 'This interactive example turns three signals—memory, disk space, and a service state—into a readable status report.': 'Цей інтерактивний приклад перетворює три сигнали — пам’ять, місце на диску та стан сервісу — на зрозумілий звіт.', 'What I’m practicing': 'Що я практикую', 'Investigating system and service behavior.': 'Дослідження поведінки системи та сервісів.', 'Reading memory and disk usage.': 'Аналіз використання пам’яті та диска.', 'Understanding systemd service status.': 'Розуміння статусів сервісів systemd.', 'Using Bash to make repeatable checks.': 'Використання Bash для повторюваних перевірок.', 'Interpreting exit codes and documenting findings.': 'Інтерпретація кодів виходу та документування результатів.', 'Linux administration': 'Адміністрування Linux', 'Service troubleshooting': 'Діагностика сервісів', 'Automation fundamentals': 'Основи автоматизації', 'Demo scope:': 'Обсяг демо:', 'the health-check tool uses sample inputs in this browser. A standalone health-check script has not been linked, and no real machine is inspected or changed.': 'health-check використовує у браузері прикладні вхідні дані. Окремий скрипт health-check не підключено, реальна машина не перевіряється й не змінюється.', 'Proposed workflow for a Linux machine using systemd. These checks are a small learning exercise, not a complete monitoring system.': 'Запропонований workflow для Linux-машини з systemd. Ці перевірки — невелика навчальна вправа, а не повноцінна система моніторингу.', '01 / COLLECT LOCAL SIGNALS': '01 / ЗІБРАТИ ЛОКАЛЬНІ СИГНАЛИ', 'Memory': 'Пам’ять', 'Root disk': 'Кореневий диск', 'Service': 'Сервіс', '02 / EVALUATE & REPORT': '02 / ОЦІНИТИ Й СТВОРИТИ ЗВІТ', 'Bash script': 'Bash-скрипт', 'Parse values': 'Розбір значень', 'Check rules': 'Правила перевірки', 'Thresholds': 'Пороги', 'Status report': 'Звіт про стан', 'Exit 0 or 1': 'Вихід 0 або 1', 'Demo rules:': 'Правила демо:', 'warn when memory or disk usage is at least 80%, or when the example service is inactive. A production-ready script would also handle command errors and missing services explicitly.': 'попереджати, якщо використання пам’яті або диска не менше 80%, або якщо приклад сервісу неактивний. Production-ready скрипт також має явно обробляти помилки команд і відсутні сервіси.',
      'Illustrative inputs only. This demo does not inspect or change any real machine.': 'Лише прикладні вхідні дані. Демо не перевіряє й не змінює реальну машину.', 'Sample scenario': 'Приклад сценарію', 'Healthy machine': 'Система в нормі', 'Disk pressure': 'Високе використання диска', 'Service stopped': 'Сервіс зупинено', 'Custom inputs': 'Власні дані', 'Run health check': 'Запустити health check', 'Warning at ≥ 80%': 'Попередження при ≥ 80%', 'Example service is active': 'Приклад сервісу активний', 'Change inputs, then run a check': 'Змініть дані та запустіть перевірку', 'Simulated health check output': 'Симульований вивід health check', 'Sample inputs ready. Run a check to generate the report.': 'Прикладні дані готові. Запустіть перевірку, щоб створити звіт.', 'Healthy: exit 0. Any warning: exit 1.': 'У нормі: exit 0. Будь-яке попередження: exit 1.', 'Hands-on practice · simulated health check': 'Практика · симульований health check',
      'Filter projects': 'Фільтр проєктів', 'Main navigation': 'Основна навігація', 'Dmytro Poliakov, home': 'Dmytro Poliakov, головна', 'Illustrative workflow: code, build, run, observe. A learning loop, not a live deployment.': 'Приклад workflow: код, збірка, запуск, спостереження. Це цикл навчання, а не живе розгортання.', 'Code to build to run to health check': 'Від коду через збірку й запуск до health check'
    }
  }
};

// Context-complete overrides for project dialogs and technical UI labels.
Object.assign(window.PORTFOLIO_I18N.strings.pl, {
  'A small Flask service, packaged with Docker and built automatically with GitHub Actions.': 'Mała usługa Flask, spakowana w Dockerze i automatycznie budowana przez GitHub Actions.',
  'Daily Fedora administration and troubleshooting, with an illustrative lab for understanding basic system health signals.': 'Codzienna administracja Fedorą i rozwiązywanie problemów, z przykładowym laboratorium pokazującym podstawowe sygnały stanu systemu.',
  ': / and /health routes.': ': trasy / i /health.',
  ': Python base image, dependencies, and startup command.': ': bazowy obraz Python, zależności i komenda startowa.',
  '$ run-example-workflow\nChoose a scenario, then run the simulation.': '$ run-example-workflow\nWybierz scenariusz, a następnie uruchom symulację.',
  '$ ./health-check.sh\nSample inputs ready. Run a check to generate the report.': '$ ./health-check.sh\nPrzykładowe dane gotowe. Uruchom kontrolę, aby wygenerować raport.',
  'Docker image': 'Obraz Docker',
  'Build': 'Budowanie',
  'Health check': 'Kontrola stanu',
  'Shell scripting': 'Skrypty shell',
  'Junior Data Analyst': 'Młodszy analityk danych'
});
Object.assign(window.PORTFOLIO_I18N.strings.ru, {
  'A small Flask service, packaged with Docker and built automatically with GitHub Actions.': 'Небольшой Flask-сервис, упакованный в Docker и автоматически собираемый через GitHub Actions.',
  'Daily Fedora administration and troubleshooting, with an illustrative lab for understanding basic system health signals.': 'Ежедневное администрирование Fedora и диагностика проблем с учебной лабораторией для понимания базовых показателей состояния системы.',
  ': / and /health routes.': ': маршруты / и /health.',
  ': Python base image, dependencies, and startup command.': ': базовый Python-образ, зависимости и команда запуска.',
  '$ run-example-workflow\nChoose a scenario, then run the simulation.': '$ run-example-workflow\nВыберите сценарий и запустите симуляцию.',
  '$ ./health-check.sh\nSample inputs ready. Run a check to generate the report.': '$ ./health-check.sh\nПримерные данные готовы. Запустите проверку, чтобы создать отчёт.',
  'Docker image': 'Docker-образ',
  'Workflow': 'Рабочий процесс',
  'Health check': 'Проверка состояния',
  'Shell scripting': 'Shell-скрипты',
  'Junior Data Analyst': 'Младший аналитик данных'
});
Object.assign(window.PORTFOLIO_I18N.strings.uk, {
  'A small Flask service, packaged with Docker and built automatically with GitHub Actions.': 'Невеликий Flask-сервіс, упакований у Docker та автоматично зібраний через GitHub Actions.',
  'Daily Fedora administration and troubleshooting, with an illustrative lab for understanding basic system health signals.': 'Щоденне адміністрування Fedora та діагностика проблем із навчальною лабораторією для розуміння базових показників стану системи.',
  ': / and /health routes.': ': маршрути / та /health.',
  ': Python base image, dependencies, and startup command.': ': базовий Python-образ, залежності та команда запуску.',
  '$ run-example-workflow\nChoose a scenario, then run the simulation.': '$ run-example-workflow\nВиберіть сценарій і запустіть симуляцію.',
  '$ ./health-check.sh\nSample inputs ready. Run a check to generate the report.': '$ ./health-check.sh\nПрикладні дані готові. Запустіть перевірку, щоб створити звіт.',
  'Docker image': 'Docker-образ',
  'Workflow': 'Робочий процес',
  'Health check': 'Перевірка стану',
  'Shell scripting': 'Shell-скрипти',
  'Junior Data Analyst': 'Молодший аналітик даних'
});
